### ISSUE TITLE
Make label for agreement checkbox clickable

### ISSUE THREAD

**Issue by Bojo966** [madsciencebulgaria/mad-science-website-react#27]
![screenshot from 2018-12-28 21-45-17](https://user-images.githubusercontent.com/8035542/50526317-f8d6df80-0ae9-11e9-9a73-9a88bde7ae0c.png)
Make so that when the label is clicked, it selects the checkbox.

**Comment by DidiMilikina** [comment]
Edited the checkbox and committed the changes.
Closing the issue.
